### ISSUE TITLE
Rearrange order of TabNine suggestions relative to VSCode suggestions

### ISSUE THREAD

**Issue by vegerot** [codota/tabnine-vscode#125]
**please complete the following information:**	
 - OS version: [e.g Mac Catalina]	
 - Editor version [e.g. 1.48.0-insider]:	
 - Programming language: [e.g. ts, vue]	
 - TabNine extension version: latest

**Issue Details:**
I love TabNine, and use it all the time.  However, if I'm doing something like completing function members `foo.ba`, I find that VSCode's Typescript Language Server provides much better suggestions than TabNine, even with TabNine's language-aware features.  Is there a way that I can have TabNine's suggestions below TS's, so that I can use TabNine when the LSP fails to be useful.  I find TabNine to be most useful when LSP fails.

**Comment by yanir-codota** [comment]
duplicates https://github.com/codota/tabnine-vscode/issues/70

**Comment by vegerot** [comment]
@yanir-codota I see that it's a duplicate, but that's been open for over six months with no response so far

**Comment by ananis25** [comment]
I'd second this. Especially when you're playing with newer packages and don't already have a lot of project code, Tabnine suggestions are more of a hindrance.

**Comment by avichay77** [comment]
@vegerot @ananis25  we're are currently in the process of reviewing this and other related issues.  Any specific example (screenshot) can be helpful to understand the full picture.

**Comment by ananis25** [comment]
Thanks for looking at this @avichay77. Here is an example. 

![tabnine-screenshot](https://user-images.githubusercontent.com/16446513/92439965-5da47180-f1c9-11ea-80e3-35b1f4579d4b.png)

While in this specific case, I've used numpy for a bit and know that `random` is a valid module; this is really distracting when working with a new package since I don't know which attributes/methods suggested by TabNine are actually present. And often I have to go back and re-enter the method I really want to use. 
To be clear, it is not an issue with the VsCode plugin but TabNine in general, so I've refrained from using it in an exploratory environment like Jupyter where increasingly I spend the most time typing. 


The original suggestion by @vegerot would be useful here since the LSP server suggestions are always legal, and TabNine can be prompted to fill in the rest of the expression after the member/method has been selected.

**Comment by vaclavbenes** [comment]
Priority up 👍

**Comment by mgmgpyaesonewin** [comment]
Currently, we can use this `"editor.snippetSuggestions": "top"` as workaround. I am not sure that it will have some issues with other setting or configuration.

So, put this line in user setting. (i.e settings.json)
```
  "editor.snippetSuggestions": "top"
```

<img width="753" alt="tabnine" src="https://user-images.githubusercontent.com/12793202/95006810-445add80-062e-11eb-9a83-47cb143a8986.png">

After changing the setting, TabNine completion will come only after the vscode completion.

**Comment by ananis25** [comment]
@avichay77 - could you give us an update here? Using tabnine in Jupyter is really inconvenient presently.

**Comment by Oscar-Silva** [comment]
any update?

**Comment by xiaoyureed** [comment]
I meet the same problem. I want to select the 6th line without press the down arrow.
<img width="553" alt="tabnine_issue" src="https://user-images.githubusercontent.com/19821471/105464307-4e334a00-5ccc-11eb-8d47-1840d21d9cbc.png">

**Comment by vegerot** [comment]
> I meet the same problem. I want to select the 6th line without press the down arrow.
> 
> <img width="553" alt="tabnine_issue" src="https://user-images.githubusercontent.com/19821471/105464307-4e334a00-5ccc-11eb-8d47-1840d21d9cbc.png">
> 
> 

@avichay77 This is EXACTLY what I'm talking about.  I get this all the time

**Comment by fungiboletus** [comment]
If the project manager is reading this, FYI I disabled tabnine in vscode, and I'm therefore not going to subscribe to Tabnine Pro, because of this issue.

**Comment by sergei-dyshel** [comment]
FYI, posted some very complex solution to this problem in https://github.com/codota/tabnine-vscode/issues/70

**Comment by IagoLast** [comment]
I had to uninstall because of the same issue. I use typescript a lot and tabnine was interfering with the ts-autocomplete.

**Comment by dimacodota** [comment]
Hi All, we just released an experimental "inline Completions" feature 🎉 

Please share your experience with this feature [here](https://github.com/codota/TabNine/issues/432) 🙏 

In order to enable it: 
 - make sure you are using the latest engine(3.5.37) and extension(3.4.21) version.
 - open the Tabnine  Home, scroll to "General Preferences" and check the "inline Completions"  option
 - restart vscode
 
<img width="1246" alt="Screen Shot 2021-08-08 at 11 15 14" src="https://user-images.githubusercontent.com/60742964/128625904-da021af1-dbd9-48f8-907e-d2713486ea36.png">
