### ISSUE TITLE
A new service is created a new window is opened. It's feature or bug?

### ISSUE THREAD

**Issue by roojay520** [codota/tabnine-vscode#134]
**please complete the following information:**	
 - OS version: macOS Mojave 
 - Editor version: v1.48.1
 - Programming language: js
 - TabNine extension version: v2.9.2

**Issue Details:**
My computer memory is overwhelmed when I have two windows open, it's possible to merge the services into one?

![image](https://user-images.githubusercontent.com/11495164/90845375-838fe080-e398-11ea-945f-e1c55e76c186.png)
![image](https://user-images.githubusercontent.com/11495164/90845916-a2db3d80-e399-11ea-9738-e3083481905d.png)

**Comment by svipas** [comment]
It creates TabNine process each time new VS Code window is opened, because it spawns child and attaches to the process so it could communicate with it (stdin/stdout). I had some ideas to fix this issue.

Imagine we have 2 windows, A and B.

1. If user changes from A window to B window. Active window now is B, it runs timer and if after N time for e.g. 5 minutes window A is inactive it kills process and keeps only process in active window B. This approach fixes the issue and it keeps only 1 process active which means you could spawn as much windows as you want, but it will have only 1 process at the time. It could also kill it instantly you switch to another window. **BUT** the main problem with TabNine is, it's not persistent and doesn't contain any cache which means it again scans all your project, etc. if project is small no problem, but if it's big it can cause problems and it takes some time to initialize everything on TabNine side.

2. I like this approach more, I don't know how it would work from TabNine side. It spawns only 1 process using TCP or UDP instead of IPC. Which means we can communicate through network card using HTTP calls and keep only 1 active process for N VS Code windows. We will not have problem mentioned above, because we don't kill process so it doesn't have to initialize every time. But the main question how TabNine will handle this I don't know, because the same process will be in charge of different projects.

**Comment by amircodota** [comment]
While this is currently the expected behavior of TabNine, we are aware that it is problematic and we are working on a fix that should be out in a little while.

In this fix, we will still have a tabnine process for each open window. However most of the memory in the tabnine process is consumed by our local deep model. Once the fix is out, those two processes will share the same deep model, which will run in its own process, thus alleviating much of the pain you describe.

In the meantime, you can consider disabling tabnine deep local option, or moving from deep local to the deep cloud (a paid option).

**Comment by chasewalden** [comment]
Is there no way to share the process between multiple windows? loopback tcp / unix domain socket maybe? or have a PID file?

Recently upgraded to deep cloud, so I expect it to be a bit less taxing on my poor 2-core laptop, but I'm glad its being looked at for the Deep Local use-case

**Comment by svipas** [comment]
@amircodota good news! This will improve TabNine a lot, especially working with several windows opened.

**Comment by roojay520** [comment]
@amircodota  thx. this will save my poor memory 👍

**Comment by boaz-codota** [comment]
Bumping the issue just to let you all know that @amircodota has made huge progress on this and it we are currently dog fooding on the implementation! Expect this fixed soon enough 🥳

**Comment by roojay520** [comment]
Good news!
