### ISSUE TITLE
Bug: If autocomplete entry contains a single quote, then the single quote is duplicated at the end of the string.

### ISSUE THREAD

**Issue by universemaster** [codota/tabnine-vscode#152]
- OS version: 10.15.5 (19F101)
- Editor version : 1.50.1
- Programming language: Markdown
- TabNine extension version: 3.1.11
--

1. I type:
Multiply Be

2. I press tab to select **Bezout's identity**
(note this looks OK in the dropdown, and does not contain an additional single quote at the end of the string).

3. I get:
Multiply Bezout's identity'

(with the cursor between the y and the end single quote.)

I should get:
Multiply Bezout's identity

I should not get the extra single quote at the end of the complete entry.

This occurs regularly on other examples, and is not to do with bad source data.  For example my files do not contain any example of the text **Bezout's identity'** ending in a single quote.

This bug still occurs even with the following settings:

"editor.autoClosingOvertype": "never"
"editor.autoClosingQuotes": "never"
"editor.autoSurround": "never"

**Comment by boaz-codota** [comment]
Hey @universemaster thanks for submitting this issue!

This is some tough nuance to solve, as this origins from Tabnine's intentional behaviour to close opened quotation marks, brackets etc. 

I reported this bug, and we will do our best to solve this, but it is worth saying that although this bug looks naive and easy to solve, it is hard to identify the correct settings in which to decide whether or not the quote should be closed (where currently we default to always close).

Sorry for not having good news regarding that behaviour. Boaz.

**Comment by universemaster** [comment]
Thanks for the comment.  I don't understand why this issue has been closed, though?
