### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by anilkumar541** [codota/tabnine-vscode#278]
- Issue Type: `Bug`
- Extension Name: `tabnine-vscode`
- Extension Version: `3.1.23`
- OS Version: `Windows_NT ia32 10.0.17763`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Eransho** [comment]
Can you share more details?

**Comment by senlinding** [comment]
![image](https://user-images.githubusercontent.com/4864830/106225009-3d7c5a00-621f-11eb-9098-c0f6f8d28019.png)

**Comment by senlinding** [comment]
@Eransho performance issue

**Comment by senlinding** [comment]
![image](https://user-images.githubusercontent.com/4864830/106225085-5f75dc80-621f-11eb-9e78-8d26baecfea5.png)

**Comment by yonip23** [comment]
Hi @senlinding, 
I've got a few questions in order to understand your case, if that's ok:
- Which engine version are you using? (Available in Tabnine hub under section "Installation Info"->"Engine Version", should be something like `3.3.42-40`)
- How long are you experiencing this issue? since when it's started?
- How often is this issue occurring? (e.g once a day / ... / all the time) 

In addition, if you could open your config file (The location of which is shown in Tabnine hub under section "Installation Info"->"Config file path") and attach here the value of the field `creation_time` - that'd be great!

Best regards

**Comment by senlinding** [comment]
![image](https://user-images.githubusercontent.com/4864830/106724354-1a98de00-6643-11eb-8cf8-1401a293e110.png)

**Comment by senlinding** [comment]
![image](https://user-images.githubusercontent.com/4864830/106724627-62b80080-6643-11eb-893d-3a56bdc32e8b.png)

**Comment by senlinding** [comment]
I am using the default configuration. This problem occurs particularly frequently, basically as soon as this extension is enabled. There are many similar situations with this extension on the web. @yonip23

**Comment by senlinding** [comment]
![image](https://user-images.githubusercontent.com/4864830/106743496-6bb3cc80-6659-11eb-9312-da5c3501334b.png)

**Comment by senlinding** [comment]
From windows ssh remote to linux.

**Comment by linonetwo** [comment]
This happened in every new version, because it is not fixed.
