### ISSUE TITLE
Not Available for Visual Studio Community/Pro/Enterprise

### ISSUE THREAD

**Issue by b9chris** [codota/tabnine-vscode#35]
Just adding this here so I can follow it for when it's released for regular (non-Code) Visual Studio. Guessing I'm not the only one who's interested.

(for those who don't use Visual Studio, the Code edition is nothing like regular Visual Studio, with a subset of features and very little overlap in terms of infrastructure).

**Comment by mlsmith007** [comment]
Same here. Would love to see a Visual Studio version.

**Comment by brianjlacy** [comment]
+1 Very anxious for Visual Studio 2019 support!

**Comment by yoshiask** [comment]
This has already been suggested, and for some reason the issue was closed even though zero progress has been made.

https://github.com/codota/TabNine/issues/101

**Comment by asheroto** [comment]
Would love to see support for VS!

**Comment by boaz-codota** [comment]
We are trying to gauge community demand, so anyone wanting visual studio plugin, please star the dedicated repository:
https://github.com/codota/tabnine-visual-studio

**Comment by CatalinRadoi** [comment]
Visual Studio is so much better than Visual Studio Code, if you have Windows. 

I know I am not alone, I know a lot of programmers just like me. We need this extension for Visual Studio as well!

**Comment by shaigeva** [comment]
I'm Happy to announce that Tabnine for Visual Studio has been released!

Marketplace page: https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-visual-studio
Installation instructions: https://www.tabnine.com/install/visualstudio
Repo for feedback / issues: https://github.com/tabnine/tabnine-visual-studio/

**Comment by sparkydasrath** [comment]
Hi @shaigeva  
Thanks for the update. 

Version: [0.1.13](https://github.com/sparkydasrath/spkfakecdn/blob/main/t9_02.png)
Auto-complete: does not work [ctrl+space](https://github.com/sparkydasrath/spkfakecdn/blob/main/t9_01.png)

> "Try to type “tabnine::config” and then ctrl+space in Visual Studio (any file, any place in the file)?"

Nope: only works on .txt file. Took me a while to get this one sorted out as I was talking to T9 support about it. As suggested to them, I highly recommend adding the bit about executing `tabnine::config` on a `.txt` file as it doesn't just work anywhere (at least not for me)

Additionally, I have not seen a SINGLE change in my Visual Studio to indicate that it is actually working. As previously said, when using it in VS Code + Rust, I get tons of Tab9 suggestions. In Visual Studio + C#, I get ZERO. I bought this mostly because my day to day is .NET Core + C# code and was hoping to help speed things up but so far it hasn't done anything.

Not sure if it's relevant, I also have Resharper & CodeMaid as helper extensions installed.

Looking forward to getting this to work...

**Comment by shaigeva** [comment]
@sparkydasrath thanks for the comments.

The issue with your setup is Resharper.
Whenever Resharper is installed, Tabnine doesn't work in C# files, as Resharper takes over the standard mechanisms. 

This is actually the top item on the agenda for the Visual Studio plugin and I'm working on it right now. I hope to have news about it soon.

Thanks,
Shai

**Comment by sparkydasrath** [comment]
@shaigeva 
Thanks for the quick response and I kinda figured R# would have been the case. For funsies, I will disable it and try to use T9 on C# files for a bit to better understand the experience. I am liking it a lot for Rust so far.

**Comment by r-sayar** [comment]
> @sparkydasrath thanks for the comments.
> 
> The issue with your setup is Resharper. Whenever Resharper is installed, Tabnine doesn't work in C# files, as Resharper takes over the standard mechanisms.
> 
> This is actually the top item on the agenda for the Visual Studio plugin and I'm working on it right now. I hope to have news about it soon.
> 
> Thanks, Shai

Will you post on the thread when it works with ReSharper?

**Comment by shaigeva** [comment]
Sorry for delay @r-sayar - will definitely update here and tag.
