### ISSUE TITLE
Partial support, click to resolve

### ISSUE THREAD

**Issue by jabbalaci** [codota/tabnine-vscode#438]
I use Tabnine with VS Code and I get the warning "Partial support, click to resolve" at the bottom. What does it mean exactly?

If I click on it, a web page opens in VS Code. The page says "Don't worry! You can still enjoy Tabnine's deep completions using our cloud - it's free!". Below it there is a link "Sign In / Sign Up and Enable Deep Completions Cloud". I signed up, logged in, but then what? How to enable "Deep Completions Cloud"? Do I need it at all? More info about it would be really useful.

**Comment by valdeniomarinho** [comment]
Dude, that message is really annoying as fuck, I have many other extensions showing up in the status bar, and that message takes too MUCH of space... It really sux!

**Comment by boaz-codota** [comment]
You can find further information here: https://www.tabnine.com/faq#fma_instructions

We suggest that you use the cloud because your computer can not run Tabnine Completions Local model.

After signup you just need to make sure that the checkbox is filled under Deep Completions Cloud:
![image](https://user-images.githubusercontent.com/69103343/112841199-e3760480-90a8-11eb-910e-b773524cfbef.png)

Let me know if you have any more questions.

**Comment by laundmo** [comment]
to answer this question:
> What does it mean exactly?

it means that your machine is not powerful enough to run the deep model locally.

**Comment by jabbalaci** [comment]
@laundmo Thanks. But then, if I click on it and I get redirected to a site, then it should be indicated on the site clearly.

**Comment by laundmo** [comment]
> 
> 
> @laundmo Thanks. But then, if I click on it and I get redirected to a site, then it should be indicated on the site clearly.

to be fair, the page that @boaz-codota linked https://www.tabnine.com/faq#fma_instructions basically says that - your machine doesn't support the instructions that tabnine needs
