### ISSUE TITLE
TabNine semantic installation on windows

### ISSUE THREAD

**Issue by Lunchb0ne** [codota/tabnine-vscode#45]
So even after the install of the language-server (atleast for html, css, scss and js ones)

The semantic completion still fails to work properly and shows the install failed error.

This isssue is on Windows.

**Comment by Lunchb0ne** [comment]
I was able to fix this issue by appending .cmd due to how the folder structure is
![image](https://user-images.githubusercontent.com/22198661/62832779-c1faa780-bc3c-11e9-9f70-9fd6ea5d5d66.png)

how my .toml file looks now
![image](https://user-images.githubusercontent.com/22198661/62832834-71d01500-bc3d-11e9-9370-6fe5304598b7.png)


This has solved the semantic completion issue on Windows for me.

**Comment by Gameghostify** [comment]
Thanks so much, semantics work for me now as well!

**Comment by Don-Osipov** [comment]
Works for me now too! Thanks a lot man, I was pretty confused with the docs.

**Comment by stared** [comment]
@Lunchb0ne Where is the folder you refer to?

**Comment by Lunchb0ne** [comment]
> @Lunchb0ne Where is the folder you refer to?

The folder where your global node cmdlets are stored.

It's generally %appdata%/npm/

**Comment by KEMBL** [comment]
Windows 10 x64
In my case problem was that Tabnine tried to start  typescript-language-server.exe  instead of typescript-language-server.cmd, adding proper extension fixes that, result:

[language.typescript]
command = "typescript-language-server.cmd"
args = ["--stdio"]
install = [["npm", "install", "-g", "typescript-language-server"]]
