### ISSUE TITLE
Prediction breaks the code

### ISSUE THREAD

**Issue by stantretyakov** [codota/tabnine-vscode#660]
- OS version: Windows 10 Pro 2004 Build 19041.1231
- Editor version: 1.61.1
- Programming language: PowerShell
- TabNine extension version: 3.4.30

Last couple of days, the prediction completely breaks my code by adding empty strings every time when I try to type more than  2 symbols from the keyboard.
Here is the prediction after the 1st symbol:
![image](https://user-images.githubusercontent.com/39192071/137599838-63a00c17-3a6a-4e14-bfd3-ffc6c3e1be5d.png)
Here is after second:
![image](https://user-images.githubusercontent.com/39192071/137599866-b42fc131-b287-4885-860f-5ef3ba3b0c5f.png)
To roll back to my initial entry, I have to press CTRL+Z several times (3-5).
Tried to downgrade the extension to the previous version - didn't help.

The only way to avoid such issue is to disable the extension.

I'm the user of the Pro version, so I'm looking forward for the fast support response
[TabinineLogs.txt](https://github.com/codota/tabnine-vscode/files/7358166/TabinineLogs.txt)

gz#7696

**Comment by yonip23** [comment]
Hi @stantretyakov 
First of all, if you're having trouble using our inline mode you can disable it in the Hub -> general preferences. Just remember to reload your VSCode afterwards. 
In order to improve on our UX, it'd be helpful if you could share here the following:
- Your config file (The path of which can be found in the Hub -> installation info)
- Your installation info section from the hub (can be a screenshot / text, doesn't matter)

Thanks a lot, have a good one
