### ISSUE TITLE
Order of suggestion

### ISSUE THREAD

**Issue by Immugio** [codota/tabnine-vscode#70]
Is there any way to control the order of suggestions? At the moment the plugin puts the suggestions produced by TabNine at the beginning of the list. I'd prefer to have them at the end since often they are less relevant than suggestions that come e.g. from properties of an object.

**Comment by anderson-custodio** [comment]
It would be really great!

**Comment by avichay77** [comment]
@Immugio @anderson-custodio, all:  can you share specific examples (language, screenshots) where TabNine suggestions on top are not optimal?

**Comment by Immugio** [comment]
@avichay77 the TabNine order of suggestion on its own is great. But I'd like all suggestion produced by TabNine to go below suggestion produced by other features of VS code.

E.g. I'd like all TypeScript generated suggestions first as they are context specific. And then all TabNine suggestions to follow after that as they are more generic and don't understand the context in which they are being used.

This issue is a blocker for me. I had to stop using this otherwise great plugin due to that.

**Comment by marian2js** [comment]
@avichay77 here is an example of this issue with TypeScript.

I'm returning a known type in which the only accepted key starting with `o` is `outputs`.

<img width="501" alt="" src="https://user-images.githubusercontent.com/4909681/99130451-16829480-25ef-11eb-879b-6b695bed4b86.png">

If I'd select `operation` which is the first suggestion, I'd get this ts error:

```
Type '{ operations: any; }' is not assignable to type 'RunResponse'.
  Object literal may only specify known properties, and 'operations' does not exist in type 'RunResponse'.ts(2322)
```

**Comment by rcoundon** [comment]
Agreed, this is a bit of a dealkiller for me. When using TypeScript, the IDE autosuggestions for properties within the object I'm working are more relevant and accurate than Tabnine's suggestions and so I need them to appear first in the list.

**Comment by marian2js** [comment]
I worked around the issue by limiting Tabnine's suggestions to 3. Still, they appear first, but at least I never entirely lose the IDE's suggestions.

**Comment by sergei-dyshel** [comment]
I studied this problem a bit some time ago and came to conclusion that it's impossible to do this ordering just by tweaking the plugin code as VSCode orders completions mostly by *score* which is calculated based on completion test and not hints that completion plugin give him (e.g. `sortText`). 

Since I didn't want to give up on Tabnine (the idea of powering auto-completion with AI is really ingenious) I decided to invest into tweaking VSCode source code. This led  to 2 forks:

- [Fork of VSCode](https://github.com/sergei-dyshel/vscode) that manipulates VSCode internal completion scoring mechanism to put Tabnine completion in the top/bottom of the list (configurable). The fork has other unrelated tweaks, for Tabnine changes are contained in https://github.com/sergei-dyshel/vscode/commit/2357e417afa24c3be156c8053289c12b797c1ffd.
- [Fork of Tabnine plugin](https://github.com/sergei-dyshel/tabnine-vscode) which adds some configuration options for fine-grained control of how plugin works per-language or per-workspace and also makes VSCode tweak work.

Unfortunately because of VSCode source change this solution is unlikely to be merged  so I'm posting it only for completion geeks like me :)

There is some history of this change in  https://github.com/codota/tabnine-vscode/issues/6.

**Comment by vegerot** [comment]
@sergei-dyshel do you have any plans to open PRs for these?

**Comment by sergei-dyshel** [comment]
@vegerot 
No. As I said, my solution is a hack.

**Comment by vegerot** [comment]
@sergei-dyshel FeelsBadMan

**Comment by dipakparmar** [comment]
Any update on this?

**Comment by kanimaru** [comment]
Removed this awesome plugin cause the suggestion order is annoying. To bad I like the some of the suggestions.

**Comment by DanteMarshal** [comment]
I'm thinking of disabling or removing Tabnine too.
Tabnine is supposed to help developers waste less time, while without this feature it actually wastes more time to pay attention to all the suggestions, scroll down and find the most relevant one.
If there's any plan for this feature (which doesn't seem likely) tell people here so at least we won't uninstall the plugin and wait for the feature.

**Comment by krailler** [comment]
I have the same issue here using typescript

**Comment by dimacodota** [comment]
Hey all, we are working on a solution for this, it will be released to beta in our upcoming release, stay tuned

**Comment by icarlosrigoni** [comment]
i am stopping use tabnine for this reason

**Comment by dimacodota** [comment]
Hi All, we just released an experimental "inline Completions" feature 🎉 

Please share your experience with this feature [here](https://github.com/codota/TabNine/issues/432) 🙏 

In order to enable it: 
 - make sure you are using the latest engine(3.5.37) and extension(3.4.21) version.
 - open the Tabnine  Home, scroll to "General Preferences" and check the "inline Completions"  option
 - restart vscode
 
<img width="1246" alt="Screen Shot 2021-08-08 at 11 15 14" src="https://user-images.githubusercontent.com/60742964/128625904-da021af1-dbd9-48f8-907e-d2713486ea36.png">

**Comment by eliezedeck** [comment]
... and I just stopped my Pro subscription.

**Comment by lorenzo-w** [comment]
Just tried tabnine after someone recommended it to me, yet the average quality of the suggestions I receive now is lower than before, as tabnine displaces all the (usually far more relevant) MyPy Typing suggestions in Python as well -> removing it.

**Comment by eliezedeck** [comment]
Anybody can tell me, is this resolved yet? I don't want to burn money just to try if it's now possible to set the order of suggestions.

**Comment by sergei-dyshel** [comment]
As I mentioned earlier in https://github.com/codota/tabnine-vscode/issues/70#issuecomment-798981147, this problem is not fixable without modifying vscode's code itself.

**Comment by vegerot** [comment]
@sergei-dyshel Is anybody on the Codota team (or other contributors) willing to contribute this to VSCode, then?

**Comment by sergei-dyshel** [comment]
> @sergei-dyshel Is anybody on the Codota team (or other contributors) willing to contribute this to VSCode, then?

I'm not aware of such attempts, but can't speak for Codota team, as I'm not related to them.

**Comment by andrei-zgirvaci** [comment]
> As I mentioned earlier in [#70 (comment)](https://github.com/codota/tabnine-vscode/issues/70#issuecomment-798981147), this problem is not fixable without modifying vscode's code itself.

Emmet has a similar feature, maybe it's worth looking into it? https://code.visualstudio.com/docs/editor/emmet#_emmet-suggestion-ordering
