### ISSUE TITLE
Tabnine use 100% CPU when I have a large array in a JS file

### ISSUE THREAD

**Issue by OB42** [codota/tabnine-vscode#794]
Ubuntu 18.04
Javascript
Tabnine 3.5.26
VS code 1.63.2

Hi,
I get 100% CPU usage indefinitely when I work on a javascript file with a large array of strings inside it.
It might be nice to just ignore large arrays when doing autocompletion? doesn't seem that useful to take them into account

Thanks

gz#12631

**Comment by maya-tabnine** [comment]
Hi @OB42 first of all if you suffer from high CPU  and memory usage, try enabling the cloud model and disable the local model.
Second, since you use VSCode, you can try disabling specific regex at Disable_line_regex.
Go to Tabnine extension settings:
<img width="700" alt="Screen Shot 2022-03-13 at 14 56 16" src="https://user-images.githubusercontent.com/82452749/158060370-8552969a-1406-4efa-be2a-5cad467c9042.png">
