### ISSUE TITLE
Issue - command Tabnine.saveSnippet not found

### ISSUE THREAD

**Issue by skoniks** [codota/tabnine-vscode#846]
**please complete the following information:**

- OS version: Win 10,
- Editor version VSCode 1.67.2:
- Programming language: ts
- TabNine extension version: 3.5.53
- Licence: Free

**Issue Details:**

While running **Tabnine: Save Snippet** i receive and error `command Tabnine.saveSnippet not found`. Is it normal?

![image](https://user-images.githubusercontent.com/13507597/170894128-2a7b457a-01d3-4b65-9951-1bc03350e927.png)
![image](https://user-images.githubusercontent.com/13507597/170894153-f9c4f45e-4fff-4cc3-a29b-61cac447e9a6.png)

gz#14659

**Comment by Tomchanskiy** [comment]
I have same error. Who knows what is it?

**Comment by maya-tabnine** [comment]
Hi can you send us your config file? Thanks!
It should be at:
MacOS :/Users/{UserName}/Library/Preferences/TabNine/tabnine_config.json
Linux : /Users/{UserName}/Library/Preferences/TabNine/tabnine_config.json
**Windows : C:\Users\{UserName}\AppData\Roaming\TabNine\tabnine_config.json**

**Comment by skoniks** [comment]
> Hi can you send us your config file? Thanks! It should be at: MacOS :/Users/{UserName}/Library/Preferences/TabNine/tabnine_config.json Linux : /Users/{UserName}/Library/Preferences/TabNine/tabnine_config.json **Windows : C:\Users{UserName}\AppData\Roaming\TabNine\tabnine_config.json**

```json
{
  "version": "4.4.14",
  "hide_promotional_message": false,
  "beta_enabled": "No",
  "ignore_all_lsp": false,
  "creation_time": "2022-05-29T16:09:20.735674900Z",
  "guuid": "463352469a4bd46c44e0ef9de32f7c3c12850019a97969ffd4f9570d7213fdb5",
  "semantic_status": {},
  "enable_telemetry": false,
  "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": true,
  "hosted_deep_completions_enabled": "Disabled",
  "tabnine_cloud_host": null,
  "tabnine_cloud_certificate_domain": null,
  "tabnine_cloud_port": null,
  "cloud_whitelist": [],
  "num_of_suggestions": 2,
  "line_suggestions": false,
  "omit_prefix_suggestions": false,
  "api_key": null,
  "api_base_url": null,
  "binary_update_interval_seconds": null,
  "local_enabled": "Unset",
  "disable_local_when_using_battery": false,
  "hide_deep_information_message": false,
  "enable_power_saving_mode": false,
  "rate_limit_interval_seconds": null,
  "rate_limit_amount": null,
  "generation": 49,
  "local_model_size": "Small",
  "model_hash_override": null,
  "local_indexing": null,
  "heartbeat_interval_seconds": null,
  "last_service_level": "FreeCloudRegistered",
  "override_beams": null,
  "override_context_length": null,
  "onboarding": {
    "model_type": null,
    "skipped_login": false,
    "completed": false
  },
  "has_git_repos": true,
  "gusr": {
    "dgc": "463352469a4bd46c44e0ef9de32f7c3c12850019a97969ffd4f9570d7213fdb5"
  },
  "exclude_file_masks": null,
  "inline_suggestions_mode": null,
  "use_specialized_model_if_available": false,
  "empty_line_suggestions": false,
  "snippets_enabled_v2": null,
  "inline_suggestions_mode_clients": {
    "clients": [
      "vscode"
    ]
  },
  "tabnine_hub_port": 5555
}
```

**Comment by rorysan333** [comment]
I think you are giving me a lot of credit. I’d love to be able to help but I’m still learning how to learn. I had a friend of mine out of blind trust I let him “help” me with crypto. I was a professional athlete (UFC *It was a career and I was and am regarded as a legend just in case you need a preface to which I would not rest a laurel on something I’m bringing up in a blind email in reference to the fact I amNow Utilizing my brain full time while i was in the UFC I was purely developing the ego or physical but physical as a mandatory”.
Anyway I say this in hopes I haven’t lost my spot here at GitHub. I have paid since however long I’ve been a member (at least 2 years). I do remember the tab nine “pull” I don’t know what pull means even. I’d love to now let you and your very dillegent staff one have my admiration for it is as hard as it looks but I have made a small step “please stick with this I’m near done”
I can and have recognized where “whomever” used false or branching notes to alter my first smart contract I purchased for Meta Mask which was DeltaRLP and I’ve unfortunately uncovered what I already knew (my “friend whom developed my website while I was making my living as a UFC competitor winning two world titles for the IFL prior) 
I know where I can change the contract and finally get the rebadging liquidity that has evaded me for years. I literally have several of these cases that I need to learn to code in order to restore my hard work that was being guided away from my family of 2children and wife and into a 39 year old “self deemed hackers” hands so he can live downtown while I’m on unemployment. 

Please keep this as confidential as your profession allows. I have a part in the upcoming Beverly Hills Cop so while that is two months away and collecting unemployment is no more i do need the guidance of your peers at GitHUB
“If ever someone wanted to help me directly I could easily teach what I am a master at and it would be learning self defense and having fun”. That reciprocation would define this endless prattle of an email in that I mastered the physical art of combat while say at the omega my “fan friend” continued his journey on the web”. Well the trade off would seem that simple to whomever is or may be interested. Skype is doable. But anyone whom knows meta and JS file smart contract hacks would easily spot this and like my brother Jens Pulver he had the highest WOWC numbers for a while there and he came in touch with some friends that helped him.  


Please accept my apologies for such a lengthy email and no answer to your “pull request”
Best,Rory ***@***.*** 


Sent from the all new AOL app for iOS


On Thursday, June 2, 2022, 4:22 PM, SKONIKS ***@***.***> wrote:





Hi can you send us your config file? Thanks! It should be at: MacOS :/Users/{UserName}/Library/Preferences/TabNine/tabnine_config.json Linux : /Users/{UserName}/Library/Preferences/TabNine/tabnine_config.json Windows : C:\Users{UserName}\AppData\Roaming\TabNine\tabnine_config.json

{
  "version": "4.4.14",
  "hide_promotional_message": false,
  "beta_enabled": "No",
  "ignore_all_lsp": false,
  "creation_time": "2022-05-29T16:09:20.735674900Z",
  "guuid": "463352469a4bd46c44e0ef9de32f7c3c12850019a97969ffd4f9570d7213fdb5",
  "semantic_status": {},
  "enable_telemetry": false,
  "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": true,
  "hosted_deep_completions_enabled": "Disabled",
  "tabnine_cloud_host": null,
  "tabnine_cloud_certificate_domain": null,
  "tabnine_cloud_port": null,
  "cloud_whitelist": [],
  "num_of_suggestions": 2,
  "line_suggestions": false,
  "omit_prefix_suggestions": false,
  "api_key": null,
  "api_base_url": null,
  "binary_update_interval_seconds": null,
  "local_enabled": "Unset",
  "disable_local_when_using_battery": false,
  "hide_deep_information_message": false,
  "enable_power_saving_mode": false,
  "rate_limit_interval_seconds": null,
  "rate_limit_amount": null,
  "generation": 49,
  "local_model_size": "Small",
  "model_hash_override": null,
  "local_indexing": null,
  "heartbeat_interval_seconds": null,
  "last_service_level": "FreeCloudRegistered",
  "override_beams": null,
  "override_context_length": null,
  "onboarding": {
    "model_type": null,
    "skipped_login": false,
    "completed": false
  },
  "has_git_repos": true,
  "gusr": {
    "dgc": "463352469a4bd46c44e0ef9de32f7c3c12850019a97969ffd4f9570d7213fdb5"
  },
  "exclude_file_masks": null,
  "inline_suggestions_mode": null,
  "use_specialized_model_if_available": false,
  "empty_line_suggestions": false,
  "snippets_enabled_v2": null,
  "inline_suggestions_mode_clients": {
    "clients": [
      "vscode"
    ]
  },
  "tabnine_hub_port": 5555
}
