### ISSUE TITLE
ignores autoUpdate=False

### ISSUE THREAD

**Issue by mrx23dot** [codota/tabnine-vscode#890]
Issue Type: <b>Bug</b>

Tabnine ignores global settings:
    "extensions.autoCheckUpdates": false,
    "extensions.autoUpdate": false,

Very annoying that tabnine path of exe-s change and I have re-enable it every time in firewall.

Extension version: 3.5.60
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

gz#16440

**Comment by avnerbarr** [comment]
Hi @mrx23dot 

The plugin runs an agent. 

What you are describing is regards to the agent's upgrade mechanism. This agent is updated frequently and the path you are mentioning represents the agent's version. Unfortunatelly there is no way to disable updating the agent itself since it is critical for the proper functioning of the plugin. 

What I suggest is to configure the firewall on a higher-level directory.

For instance, an "allow rule" on the top-most directory of `tabnine`

Hope this helps
